# The basics

## An example

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)    # 15개의 숫자를 생성하여 3행 5열의 2차원 배열로 구조화
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape   # 배열의 형태, 3행 5열의 구조를 가지고 있음

(3, 5)

In [3]:
a.ndim       # 배열의 축(axis)의 개수, 행과 열(2개의 축) 2차원

2

In [4]:
a.dtype.name  # 데이터 타입의 이름, 배열 요소들의 자료형(64비트의 정수형)

'int64'

In [5]:
a.itemsize   # 요소당 크기, 배열의 각 요소 하나가 메모리에서 차지하는 크기(8바이트 = 64비트)

8

In [6]:
type(a)  # 배열의 객체 타입, 넘파이의 다차원 배열 객체(ndarray)임

numpy.ndarray

## Array creation

In [7]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [8]:
a.dtype

dtype('int64')

In [9]:
a.dtype.name

'int64'

In [10]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [11]:
b.dtype.name

'float64'

In [12]:
# a = np.array(1, 2, 3, 4)    wrong
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [13]:
b = np.array([(1.5, 2, 3), (4 ,5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 3, 4), dtype= np.int16)   # 3행 4열짜리 행렬이 2개

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
np.arange(10, 30, 5)   # 10이상부터 30미만까지 5씩 증가하며 나열

array([10, 15, 20, 25])

In [19]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
from numpy import pi
np.linspace(0, 2, 9)   # 0 이상부터 2 이하까지 균등하게 나눈 9개의 값으로 나열

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Printing arrays

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [24]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [25]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [26]:
import sys
arr = np.arange(1500)  # 기본값은 1000개 이상 시 생략
print(arr)             # 중간에 '...'이 포함되어 출력됨

# 설정 변경
np.set_printoptions(threshold=sys.maxsize)  # 0부터 1499까지 모든 숫자가 출력됨

[   0    1    2 ... 1497 1498 1499]


## Basic operations

In [27]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [32]:
c = a - b
c   # 같은 위치(index)에 있는 요소끼리 연산 수행됨  -> 요소별 연산

array([20, 29, 38, 47])

In [33]:
b ** 2   # b_squared = b ** 2

array([0, 1, 4, 9])

In [34]:
10 * np.sin(a)  # 배열 a의 각 요소에 sin 값을 구하고 10을 곱함 (요소별 연산)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [35]:
a < 35  # a의 각 요소가 35보다 작은지 판별하여 불리언(True/False) 배열 반환

array([ True,  True, False, False])

In [36]:
# [브로드캐스팅]
# 크기가 다른 배열끼리 연산 시, 작은 배열을 자동으로 확장하여 크기를 맞춤
# 예: [1, 2, 3] + 10  -> [1+10, 2+10, 3+10]

In [40]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B   # 같은 위치에 있는 요소끼리 단순히 곱. (행렬의 수학적 곱셈이 아님)

array([[2, 0],
       [0, 4]])

In [41]:
A @ B  # 선형대수학에서 정의하는 표준 행렬 곱셈

array([[5, 4],
       [3, 4]])

In [42]:
A.dot(B)   #A @ B와 동일한 결과

array([[5, 4],
       [3, 4]])

In [43]:
rg = np.random.default_rng(1)        # 난수 생성기 인스턴스 생성
a = np.ones((2, 3), dtype = int)     # 2행 3열의 모든 요소가 1인 정수형 배열 생성
b = rg.random((2, 3))                # 0 이상 1미만의 난수로 구성된 2행 3열 배열 생성
a *= 3                               # 배열 a의 모든 요소에 3을 곱함
a

array([[3, 3, 3],
       [3, 3, 3]])

In [44]:
b += a    # b = float, a = int   -> b = b + a  -> float = float + int 가능!
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [45]:
a += b    # a = int  b = float   -> a = a + b  -> int = int + float 불가!

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [47]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [49]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [50]:
c.dtype.name

'float64'

In [51]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [52]:
d.dtype.name

'complex128'

In [53]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [55]:
a.sum()

np.float64(3.1057109529998157)

In [56]:
a.min()

np.float64(0.027559113243068367)

In [57]:
a.max()

np.float64(0.8277025938204418)

In [58]:
b = np.arange(12).reshape(3, 4)   # 3행 4열의 2차원 배열 생성
b   

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b.sum(axis = 0)       # axis = 0, 세로 방향 연산 수행-> 열(col)을 따라 합계 계산

array([12, 15, 18, 21])

In [60]:
b.min(axis = 1)     # axis = 1, 가로 방향 연산 수행-> 행(row)을 따라 최솟값 계산

array([0, 4, 8])

In [61]:
b.cumsum(axis = 1) # axis = 1, 가로 방향 연산 수행-> 행(row)을 따라 누적 합계 계산

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal functions