## No copy at all

In [1]:
import numpy as np
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
b = a
b is a

True

In [2]:
def f(x):
    print(id(x))

id(a)

2272803255664

In [3]:
f(a)

2272803255664


## View or shallow copy

In [5]:
c = a.view()
c is a

False

In [6]:
c.base is a

True

In [7]:
c.flags.owndata

False

In [8]:
c = c.reshape((2, 6))
a.shape

(3, 4)

In [9]:
c[0, 4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [10]:
s = a[:, 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Deep copy

In [11]:
d = a.copy()
d is a
d.base is a

False

In [12]:
d[0, 0]
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [15]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

## Functions and methods overview

- Array Creation
 > arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

- Conversions:
    > ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

- Manipulations:
    > array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

- Questions:
    > all, any, nonzero, where

- Ordering:
    > argmax, argmin, argsort, max, min, ptp, searchsorted, sort

- Operations:
    > choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

- Basic Statistics:
    > cov, mean, std, var

- Basic Linear Algebra:
    > cross, dot, outer, linalg.svd, vdot