## No copy at all

In [1]:
import numpy as np
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
b = a                                # a, b 같은 배열을 두 이름으로 가리킴(복사 아님)
b is a                               # True. b는 a이다. (b 수정하면 a도 변경됨)

True

In [2]:
def f(x):
    print(id(x))   # 매개변수 x의 메모리 주소 출력

id(a)              # a의 메모리 주소 반환

2212406256016

In [3]:
f(a)              # a의 메모리 주소 반환 (=id(a))

2212406256016


## View or shallow copy

In [4]:
c = a.view()          # a의 view 생성(얕은 복사, 새로 만들지 않고 메모리 공유)
c is a                # False. c와 a는 다른 객체

False

In [5]:
c.base is a           # True. 데이터는 a를 참조

True

In [6]:
c.flags.owndata # owndata: 소유권 유무 판단
# 복사 -> 새 메모리 할당 -> 소유권 있음 : True
# 연결(view) -> 원본 메모리 참조 -> 소유권 없음 : False

False

In [7]:
c = c.reshape((2, 6))   # c를 2행 6열로 재배치
a.shape                 # a의 배열 형태

(3, 4)

In [8]:
c[0, 4] = 1234          # c의 0행 4번째를 1234로 변경
a                       # a 출력 → c가 a의 뷰이므로 a[1, 0] 값도 1234로 반영됨

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [9]:
s = a[:, 1:3]  # a의 모든 행(:), 1~2열 슬라이싱 ( ','쉼표 기준 앞(=행), 뒤(=열) -> 뷰 생성
s[:] = 10      # s의 모든 값(쉼표없으면 전체 의미)을 10으로 변경
a              # a 출력-> s가 뷰-> a의 1~2열도 10으로 반영됨

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Deep copy

In [10]:
d = a.copy()          # a를 복사-> 새 메모리 할당
d is a                # False. d와 a는 다른 객체
d.base is a           # False. d는 독립적이라 base가 None, 메모리 연결 없음

# 'is' 객체(이름표)가 같은가, 'base' 메모리가 연결됐는가

False

In [11]:
d[0, 0]  # d의 0행 0열 값 출력-> '0'원본값 그대로
a        # a출력-> d는 복사본이므로 a 변경 없음

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [12]:
a = np.arange(int(1e8))  # a = 0 ~ (10^8)-1까지의 1차원 배열 생성
b = a[:100].copy()       # b = a의 0~99번째 요소만 복사 -> 새 메모리 할당
del a                    # a 삭제 -> 10^8개짜리 메모리 반환( 이름표 없애고 데이터 지움)

## Functions and methods overview

- Array Creation
 > arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

- Conversions:
    > ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

- Manipulations:
    > array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

- Questions:
    > all, any, nonzero, where

- Ordering:
    > argmax, argmin, argsort, max, min, ptp, searchsorted, sort

- Operations:
    > choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

- Basic Statistics:
    > cov, mean, std, var

- Basic Linear Algebra:
    > cross, dot, outer, linalg.svd, vdot