# Shape manipulation

## Changing the shape of an array

In [1]:
import numpy as np
rg = np.random.default_rng(1)     # seed = 1, 난수 생성기 인스턴스 생성
a = np.floor(10 * rg.random((3, 4)))  # 3행 4열 배열로 생성, 10배 후 정수 만듦.(0 ~ 9 정수 배열)
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [2]:
a.shape   # a의 모양(행, 열) 반환

(3, 4)

In [3]:
a.ravel()    # a 배열을 1차원으로 펼침 (원본유지)

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [4]:
a.reshape(6, 2)  # a를 6행 2열로 재배열 (원본유지)

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [5]:
a.T  # a의 전치행렬(행 ↔ 열 교환)

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [6]:
a.T.shape # a의 전치행렬의 모양(행, 열) 반환

(4, 3)

In [7]:
a.shape # a의 모양(행, 열) 반환

(3, 4)

In [8]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [9]:
a.resize((2, 6))    # 2행 6열로 재배열(원본 직접 변경)
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [10]:
a.reshape(3, -1)  # a를 3행 x열(자동계산)로 재배열 (원본유지)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [11]:
a = np.floor(10 * rg.random((2, 2)))    # a = 2행 2열 배열로 생성, 10배 후 정수 만듦.(0 ~ 9 정수 배열)
a

array([[3., 7.],
       [3., 4.]])

In [12]:
b = np.floor(10 * rg.random((2, 2)))  # b = 2행 2열 배열로 생성, 10배 후 정수 만듦.(0 ~ 9 정수 배열)
b

array([[1., 4.],
       [2., 2.]])

In [13]:
np.vstack((a, b))  # a, b 행 방향으로 연결하여 작성 (세로 방향)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.]])

In [14]:
np.hstack((a, b)) # a, b 열방향으로 연결하여 작성 (가로 방향)

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [15]:
from numpy import newaxis
np.column_stack((a, b))   # a, b를 열 방향으로 연결

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [16]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))   # a, b를 열벡터로 변환 후 연결 -> shape(2, 2)

array([[4., 3.],
       [2., 8.]])

In [17]:
np.hstack((a, b)) # a, b를 행 방향으로 연결 -> shape(4,)

array([4., 2., 3., 8.])

In [18]:
a[:, newaxis]    # a를 열벡터로 변환 (shape (2,) -> (2, 1))

array([[4.],
       [2.]])

In [19]:
np.column_stack((a[:,newaxis], b[:, newaxis]))
# a, b 를 각각 열벡터로 변환
# 열 방향으로 연결-> shape (2, 2)

array([[4., 3.],
       [2., 8.]])

In [20]:
np.hstack((a[:, newaxis], b[:, newaxis]))
# a, b 를 각각 열벡터로 변환
# 행 방향으로 연결-> shape (2, 2)

array([[4., 3.],
       [2., 8.]])

In [27]:
np.r_[1:4, 0, 4]  # '1:4' = 'range(1,4)', row 방향으로 이어 적기

array([1, 2, 3, 0, 4])

## Splitting one array into several smaller ones

In [25]:
a = np.floor(10 * rg.random((2, 12)))   # a = 2행 12열 배열로 생성, 10배 후 정수 만듦.(0 ~ 9 정수 배열)
a 

array([[3., 0., 2., 4., 1., 6., 3., 7., 6., 4., 8., 6.],
       [8., 3., 5., 1., 9., 2., 2., 0., 2., 7., 6., 1.]])

In [26]:
np.hsplit(a, (3, 4))  # a를 열 방향(세로)으로 분할---> 0:3, 3:4, 4:x(분할 위치 지정, ':' 이후 인덱스 미포함)

[array([[3., 0., 2.],
        [8., 3., 5.]]),
 array([[4.],
        [1.]]),
 array([[1., 6., 3., 7., 6., 4., 8., 6.],
        [9., 2., 2., 0., 2., 7., 6., 1.]])]