# Shape manipulation

## Changing the shape of an array

In [1]:
import numpy as np                     # NumPy = Numerical Python
rg = np.random.default_rng(1)          # 난수 생성기 객체 생성. 
# seed값 '1' -> 실행마다 동일한 난수 순서 보장
a = np.floor(10 * rg.random((3, 4)))   #  rg.random() : 0.0 이상 1.0 미만
# 10 * rg.random((3, 4)-> 0.0 이상 10.0 미만의 3행 4열 배열
# floor -> 소수점 이하 전부 버림
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [2]:
a.shape # a의 배열 구조 확인

(3, 4)

In [3]:
a.ravel()    # 1차원으로 펼침

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [4]:
a.reshape(6, 2)   # 6행 2열 배열로 재배치 (원본 유지)
# 요소 수 같아야 함

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [5]:
a.T  # T = transpose, 전치행렬(행 렬 뒤집음 3행 4열 -> 4행 3열)

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [6]:
a.T.shape # 전치된 배열의 구조 확인 → (4, 3) : 4행 3열

(4, 3)

In [7]:
a.shape # 배열의 구조 확인 → (3, 4)

(3, 4)

In [8]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [9]:
a.resize((2, 6))  # 2행 6열로 원본 변경, 부족한 자리는 0으로 채움
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [10]:
a.reshape(3, -1) # 3행 고정, 열 수는 자동 계산
# (-1 = 열 수 자동 계산) ( 12 / 3 = 4)  --> (3,4) 

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [11]:
a = np.floor(10 * rg.random((2, 2)))  # 2행 2열 배열 생성(rg 난수 4개 뽑음)
a

array([[3., 7.],
       [3., 4.]])

In [12]:
b = np.floor(10 * rg.random((2, 2)))  # 2행 2열 배열 생성(rg에서 4개 더 뽑음)
b

array([[1., 4.],
       [2., 2.]])

In [13]:
np.vstack((a, b)) # a와 b를 수직(vertical)으로 합침

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.]])

In [14]:
np.hstack((a, b)) # a와 b를 수평(horizontal)으로 합침

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [15]:
from numpy import newaxis # newaxis : []안에서 축 추가, ()안에서는 사용 불가
np.column_stack((a, b))  # a와 b가 2차원이므로 hstack과 동일 , 옆으로 붙여 합침

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [16]:
a = np.array([4., 2.])   # 1차원 배열
b = np.array([3., 8.])   # 1차원 배열
np.column_stack((a, b))  # 1차원 -> 열로 세워 2차원으로 합침

array([[4., 3.],
       [2., 8.]])

In [17]:
np.hstack((a, b))  # 1차원 배열 -> 그냥 이어 붙임

array([4., 2., 3., 8.])

In [18]:
a[:, newaxis]  # a를 1차원에서 열 추가하여 2차원 열벡터로 변환

array([[4.],
       [2.]])

In [19]:
np.column_stack((a[:,newaxis], b[:, newaxis]))  # 각각 열 백터로 변환 후 열 방향으로 합침

array([[4., 3.],
       [2., 8.]])

In [20]:
np.hstack((a[:, newaxis], b[:, newaxis])) # 각각 열 백터로 변환 후 수평 방향으로 합침

array([[4., 3.],
       [2., 8.]])

In [21]:
np.r_[1:4, 0,4]  # 왼쪽부터 순서대로 이어붙임, ':' 끝값 미포함(n:m-> n ~ m-1 범위)

array([1, 2, 3, 0, 4])

## Splitting one array into seveal smaller ones

In [22]:
a = np.floor(10 * rg.random((2, 12)))  # 2행 12열 배열 생성

In [23]:
np.hsplit(a, 3)  # a배열을 열 방향으로 균등하게 3등분 -> (2, 4) 배열 3개 생성

[array([[7., 2., 4., 9.],
        [6., 7., 6., 9.]]),
 array([[9., 7., 5., 2.],
        [0., 5., 4., 0.]]),
 array([[1., 9., 5., 1.],
        [6., 8., 5., 2.]])]

In [24]:
np.hsplit(a, (3, 4))  
# a 배열을 3번째 4번째 위치에서 자름
# 3번 열 전(0~2번 열), 3번 열, 4번 열 ~ 끝 까지 

[array([[7., 2., 4.],
        [6., 7., 6.]]),
 array([[9.],
        [9.]]),
 array([[9., 7., 5., 2., 1., 9., 5., 1.],
        [0., 5., 4., 0., 6., 8., 5., 2.]])]