# Shape manipulation

## Changing the shape of an array

In [1]:
import numpy as np
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [2]:
a.shape

(3, 4)

In [3]:
a.ravel()    # returns the array, flattened

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [4]:
a.reshape(6, 2)

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [5]:
a.T  #returns the array, transposed

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [6]:
a.T.shape

(4, 3)

In [7]:
a.shape

(3, 4)

In [8]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [9]:
a.resize((2, 6))
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [10]:
a.reshape(3, -1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [11]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[3., 7.],
       [3., 4.]])

In [12]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[1., 4.],
       [2., 2.]])

In [13]:
np.vstack((a, b))

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.]])

In [14]:
np.hstack((a, b))

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [15]:
from numpy import newaxis
np.column_stack((a, b))

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [16]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [17]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [18]:
a[:, newaxis]

array([[4.],
       [2.]])

In [19]:
np.column_stack((a[:,newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [20]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [21]:
np.r_[1:4, 0,4]

array([1, 2, 3, 0, 4])

## Splitting one array into seveal smaller ones