# The basics

 **ndim**: 배열의 차원 수 (축의 개수)
 - 예시: 3x4 행렬의 경우 -> 2

**shape**: 각 차원의 크기 (배열의 모양)
 -  예시: 3x4 행렬의 경우 -> (3, 4)

**size**: 배열 내 전체 요소의 총 개수
 - 예시: 3x4 행렬의 경우 -> 12

**dtype**: 배열에 저장된 요소의 자료형
 - 예시: 정수형일 경우 -> int64
 
**itemsize**: 요소 하나가 차지하는 바이트(byte) 크기
 - 예시: int64 타입일 경우 -> 8
 
**data**: 실제 데이터가 저장된 메모리 버퍼
 - 예시: 직접 접근하기보다는 인덱싱을 통해 주로 사용

## An example

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)    # 15개의 숫자(0 ~ 14)값을 생성하여 3행 5열의 2차원 배열로 구조화
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape   # 배열의 형태, 3행 5열의 구조를 가지고 있음

(3, 5)

In [3]:
a.ndim       # 배열의 축(axis)의 개수, 행과 열(2개의 축) 2차원

2

In [4]:
a.dtype.name  # 데이터 타입의 이름, 배열 요소들의 자료형(64비트의 정수형)

'int64'

In [5]:
a.itemsize   # 요소당 크기, 배열의 각 요소 하나가 메모리에서 차지하는 크기(8바이트 = 64비트)

8

In [6]:
type(a)  # 배열의 객체 타입, 넘파이의 다차원 배열 객체(ndarray)임

numpy.ndarray

## Array creation

In [7]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [8]:
a.dtype

dtype('int64')

In [9]:
a.dtype.name

'int64'

In [10]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [11]:
b.dtype.name

'float64'

In [12]:
# a = np.array(1, 2, 3, 4)    wrong
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [13]:
b = np.array([(1.5, 2, 3), (4 ,5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
np.zeros((3, 4))   # 0으로 구성된 3행 4열 행렬

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 3, 4), dtype= np.int16)   # 1로 구성된 3행 4열짜리 (3차원)행렬이 2개, 모든 요소를 1(int16타입)으로 초기화

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
# np.zeros(shape)   : np.zeros((2, 3))  0으로  2행 3열 배열 생성
# np.ones(shape)    : np.ones((2, 3))  1로  2행 3열 배열 생성
# np.full(shape, n) : np.full((2, 3),7)  7로  2행 3열 배열 생성

In [18]:
np.empty((2,3)) # 2행 3열 크기 행렬, 임의의 값(Garbage, 이전에 사용되었던 데이터)으로 채워짐

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [19]:
np.arange(10, 30, 5)   # 10이상부터 30미만까지 5씩 증가하며 나열

array([10, 15, 20, 25])

In [20]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [21]:
from numpy import pi
np.linspace(0, 2, 9)   # 0 이상부터 2 이하까지 균등하게 나눈 9개의 값으로 나열

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Printing arrays

In [22]:
# arange: 'array range'의 줄임말
# arange(n)은 0부터 n-1까지의 정수 생성

a = np.arange(6)  # 0부터 5까지 1차원 배열 생성
print(a)

[0 1 2 3 4 5]


In [23]:
b = np.arange(12).reshape(4, 3)  # 0 ~ 11까지의 값을 4행 3열 형태로 생성
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [24]:
c = np.arange(24).reshape(2, 3, 4) # 0 ~ 23까지의 값을 2개의 3행4열 형태로 생성
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
print(np.arange(10000)) # 0~ 9999까지의 배열 출력(기본 설정으로 중간 생략됨)

[   0    1    2 ... 9997 9998 9999]


In [26]:
print(np.arange(10000).reshape(100, 100))  # 100 * 100 배열로 출력(중간  생략됨)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [27]:
#import numpy    수치 해석 및 배열 연산, (계산 엔진)
import sys     # 인터프리터 및 시스템 환경 제어  ( 시스템 환경 도구)

arr = np.arange(1500)  # 0 ~ 1499까지의 배열 출력
print(arr)             # 기본 설정(threshold = 1000)으로 중간 생략되어 출력
# 기본 설정 데이터 값 1000개 초과 시 생략됨

# 설정 변경
np.set_printoptions(threshold=sys.maxsize)  # 배열 전체 출력되도록 임계값 maxsize로 변경
# printoptions: 출력 규칙 제어
# threshold: 임계치 기준점
# sys.maxsize: 시스템이 지원하는 정수 최댓값(배열 크기와 무관하다. arr의 maxsize가 아니다)

[   0    1    2 ... 1497 1498 1499]


## Basic operations

In [28]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [29]:
c = a - b
c   # 같은 위치(index)에 있는 요소끼리 연산 수행됨  -> 요소별 연산

array([20, 29, 38, 47])

In [30]:
b ** 2   # b_squared = b^2(제곱) 의미
# b ^ 2: 비트 단위 XOR 연산(두 비트가 다를 때만 1 반환)(수학적 제곱 아님)

array([0, 1, 4, 9])

In [31]:
10 * np.sin(a)  # 배열 a의 각 요소에 sin 값을 구하고 10을 곱함 (요소별 연산)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [32]:
a < 35  # a의 각 요소가 35보다 작은지 판별하여 불리언(True/False) 배열 반환

array([ True,  True, False, False])

In [33]:
# [브로드캐스팅]
# 크기가 다른 배열끼리 연산 시, 작은 배열을 자동으로 확장하여 크기를 맞춤
# 예: [1, 2, 3] + 10  -> [1+10, 2+10, 3+10]

In [34]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B   # 같은 위치에 있는 요소끼리 단순히 곱. (행렬의 수학적 곱셈이 아님, 1:1 대응 곱셈)

array([[2, 0],
       [0, 4]])

In [35]:
A @ B  # 선형대수학에서 정의하는 표준 행렬 곱셈, 데이터 간의 관계를 변환하거나 조합할 떄 사용하는 행렬곱셈

array([[5, 4],
       [3, 4]])

In [36]:
A.dot(B)   #A @ B와 동일한 결과(행렬의 곱셈)

array([[5, 4],
       [3, 4]])

In [37]:
rg = np.random.default_rng(1)        # 난수 생성기 인스턴스 생성
a = np.ones((2, 3), dtype = int)     # 2행 3열의 모든 요소가 1인 정수형 배열 생성
b = rg.random((2, 3))                # 0 이상 1미만의 난수로 구성된 2행 3열 배열 생성
a *= 3                               # 배열 a의 모든 요소에 3을 곱함
a

array([[3, 3, 3],
       [3, 3, 3]])

In [38]:
b += a    # b = float, a = int   -> b = b + a  -> float = float + int 가능!
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [39]:
# a += b    
# a = int  b = float   -> a = a + b  -> int = int + float 불가!

In [40]:
a = np.ones(3, dtype=np.int32) # 1을 3개 가진 1차원의 int32 타입의 배열 a
b = np.linspace(0, pi, 3) # 0 부터 pi 까지 3등분한 배열 b 
# np.linspace(start, stop, num)
# start: 시작점, stop: 끝점(포함), num: 생성할 요소(= 등분할 수 + 1) 
b.dtype.name

'float64'

In [41]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [42]:
c.dtype.name
# .dtype: 배열의 데이터 타입 객체를 가리킴(dtype('float64'))
# .name: 해당 타입의 이름을 읽기 편한 문자열로 가져옴 ('float64')

'float64'

In [43]:
d = np.exp(c * 1j)
d
# 오일러 공식: e^(i*c) = cos(c) + i*sin(c)
# np.exp(c * 1j) : 공식의 지수 부분(i*c)을 계산하여 결과값(복소수)을 반환
# c: 각도 (회전의 양을 결정, 좌우 이동 변화량)
# 1: 높이 (상하 이동 변화량)
# j: 허수를 표기하는 기호

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [44]:
d.dtype.name

'complex128'

In [45]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [46]:
a.sum()

np.float64(3.1057109529998157)

In [47]:
a.min()

np.float64(0.027559113243068367)

In [48]:
a.max()

np.float64(0.8277025938204418)

In [49]:
b = np.arange(12).reshape(3, 4)   # 3행 4열의 2차원 배열 생성
b   

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
b.sum(axis = 0)       #열(col)을 따라 합계 계산

# 'sum.axis = 0' : 0번 축(세로)을 따라 연산-> 각 열의 합계 산출
# axis= 0은 행(row)들의 인덱스가 변하면서 연산하므로, 결과적으로 행이 사라지고 열만 남는다.

array([12, 15, 18, 21])

In [51]:
b.min(axis = 1)     # 행(row)을 따라 최솟값 계산

#'min.axis = 1' : 1번 축(가로)을 따라 연산-> 각 행의 합계 산출
# axis= 1은 열(col)들의 인덱스가 변하면서 연산하므로, 결과적으로 열이 사라지고 행만 남는다.

array([0, 4, 8])

In [52]:
b.cumsum(axis = 1) # axis = 1, 가로 방향 연산 수행-> 행(row)을 따라 누적 합계 계산

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal functions

In [53]:
import numpy as np
B = np.arange(3)
B

array([0, 1, 2])

In [54]:
np.exp(B)   # e^B

array([1.        , 2.71828183, 7.3890561 ])

In [55]:
np.sqrt(B)   # √x 또는 x^(1/2)


# np.exp(B)      : 자연상수 e를 밑으로 고정 -> e^B
# np.power(B, e) : B를 밑으로, e를 지수로 함 -> B^e
# np.square(B)   : B를 밑으로, 2를 지수로 함 -> B^2 (제곱)
# np.sqrt(B)     : B의 제곱근을 구함 -> √B (또는 B^0.5)

array([0.        , 1.        , 1.41421356])

In [56]:
C = np.array([2., -1., 4.])

In [57]:
np.add(B,C)

array([2., 0., 6.])

## Indexing, Slicing and iterating

In [58]:
a = np.arange(10) ** 3   # 0 ~ 9까지 1차원 배열 생성, 각 요소를 3제곱(cybe) 처리
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [59]:
a[2] # 인덱스 2번 '값' 하나를 추츨

np.int64(8)

In [60]:
a[2:5] # 인덱스 2번 부터 4번까지 '범위' 출력

array([ 8, 27, 64])

In [61]:
a[:6:2] = 1000    # 인덱스 0부터 6이전까지 2씩 건너뛰며 접근하여 '1000'으로 일괄 변경
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [62]:
a[::-1]  # 시작부터 끝까지 뒤에서 -1칸씩 이동

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [63]:
for i in a:
    print(i ** (1/3.))

# [역정규화(Denormalization) 및 복원]  'i ** (1/3.)'
# - 목적: 세제곱(x**3) 연산의 역연산으로, 원래의 데이터 단위로 '역정규화(복원)' 수행
# - 수학적 의미: i^(1/3) = 세제곱근(Cube Root)
# - 참고: 부동소수점 연산 특성상 완벽한 정수가 아닌 미세한 오차가 발생할 수 있음
#        (9.999...와 같이 출력될 경우 np.round()로 보정 가능)

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [64]:
def f(x, y):              # x: 행 인덱스 값, y: 열 인덱스 값 (좌표)
    return 10 * x + y

In [65]:
b = np.fromfunction(f, (5, 4), dtype=np.int_)
b

# [np.fromfunction]
# - 함수(x, y)의 연산 결과값들을 받아 5행 4열 2차원 배열 생성
# - int_(현재 시스템의 기본 정수 타입)의 type 형태로 지정

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [66]:
b[2, 3]  # 스칼라 인덱싱, 배열의 type 정보, 배열의 특정 위치(2행 3열)의 값 하나를 직접 추출

# 스칼라(Scalar, 단일 값, 차원이 없는 값) 인덱싱: '값' 하나를 가져오며, 그 값의 타입 정체성을 명확히 표기

np.int64(23)

In [67]:
b[0:5, 1]  # 슬라이싱, 값 하나가 아니라 '0행부터 4행까지, 1열의 데이터 범위'을 추출(부분 집합 추출)

# 슬라이싱(Slicing, 부분 집합): 값 하나가 아닌 배열의 일부분을 구조적으로 추출하며, 결과물은 여전히 '배열(Array)' 형태

array([ 1, 11, 21, 31, 41])

In [68]:
b[:,1]    # 모든 행(:)에 대하여 1열의 데이터를 가져옴

array([ 1, 11, 21, 31, 41])

In [69]:
b[1:3, :] # 1행부터 2행까지 전체 열(:)을 가져옴

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [70]:
# [인덱싱 및 슬라이싱 구분자 : 쉼표(,)]
# - 쉼표 기준 앞: 행(Row) 범위 지정///쉼표 기준 뒤: 열(Column) 범위 지정

# b[:, :]: 모든 행(:)과 모든 열(:)을 선택 -> 결과: 배열 전체
# b[0, :]: 0행의 모든 열 (1차원 배열 반환)
# b[:, 0]: 모든 행의 0열 (1차원 배열 반환)
# b[0, 0]: 0행 0열의 단일 값 (스칼라 반환)

In [71]:
b[-1]  # 뒤에서 첫 번째 행을 가져옴

array([40, 41, 42, 43])

In [72]:
c = np.array([[[0, 1, 2],[10,12,13]],
              [[100,101,102],[110,112,113]]])
c.shape

(2, 2, 3)

In [73]:
# [Ellipsis(...) 활용]
# - 원칙: 나머지 모든 차원을 '전부' 선택하며, 괄호 내 단 1회만 사용, ... 은 '생략된 차원의 뭉치'입니다.
# - 구조적 의미:c[층, 행, 열] 기준
#    c[1, ...]  → c[1, :, :]  (1번 층 고정, 나머지 전부)
#    c[..., 2]  → c[:, :, 2]  (2번 열 고정, 나머지 전부)
#    c[..., 1, ...] 과 같이 작성하면, 어느 쪽 ...이 어디까지 담당할지 모호해집니다.

In [74]:
c[1,...]   # 1번 층의 모든 행/열 슬라이싱 
# 구조: c[1, :, :]  -> 문법: c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [75]:
c[...,2]  # 모든 층/행의 2열 인덱싱  c[..., ..., 2]
# 구조: c[:, :, 2]  -> 문법: c[..., 2]

array([[  2,  13],
       [102, 113]])

In [76]:
for row in b:
    print(row)

# [for row in b]
# 행 단위로 순회, (구조 유지)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [77]:
for element in b.flat:
    print(element)

# [for element in b.flat] 
# 개별 요소 단위로 순회, 개별 데이터(스칼라)단위로 출력 (평탄화, 1차원화)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
